//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gameoflife {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl usrlabel;
		
		protected System.Web.UI.HtmlControls.HtmlForm save_form;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl loginFields;
		
		protected System.Web.UI.WebControls.TextBox emailInput;
		
		protected System.Web.UI.WebControls.TextBox pwdInput;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator emailValidator;
		
		protected System.Web.UI.WebControls.HiddenField aliveCells;
		
		protected System.Web.UI.WebControls.HiddenField patternHeight;
		
		protected System.Web.UI.WebControls.HiddenField patternWidth;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl shareDiv;
		
		protected System.Web.UI.WebControls.HiddenField loggedUserId;
		
		protected System.Web.UI.WebControls.TextBox descInput;
		
		protected System.Web.UI.WebControls.Button shareButton;
	}
}
