//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gameoflife {
    
    
    public partial class Guestbook {
        
        protected System.Web.UI.HtmlControls.HtmlForm usrform;
        
        protected System.Web.UI.WebControls.TextBox nameInput;
        
        protected System.Web.UI.WebControls.TextBox commentInput;
        
        protected System.Web.UI.WebControls.Button submitButton;
    }
}
