//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gameoflife {
	
	
	public partial class SignUp {
		
		protected System.Web.UI.HtmlControls.HtmlForm usrform;
		
		protected System.Web.UI.WebControls.TextBox name;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.TextBox confirm;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator emailValidator;
	}
}
